#if K_FFT == 1
#include "./include/fft.cuh"
#include "./include/hadmard.cuh"
#include "./include/radix_2/kernel_logN=3.cuh"
#include "./include/radix_2/kernel_logN=4.cuh"
#include "./include/radix_2/kernel_logN=5.cuh"
#include "./include/radix_2/kernel_logN=6.cuh"
#include "./include/radix_2/kernel_logN=7.cuh"
#include "./include/radix_2/kernel_logN=8.cuh"
#include "./include/radix_2/kernel_logN=9.cuh"
#include "./include/radix_2/kernel_logN=10.cuh"
#include "./include/radix_2/kernel_logN=11.cuh"
#include "./include/radix_2/kernel_logN=11_reg16.cuh"
#include "./include/radix_2/kernel_logN=12.cuh"
#include "./include/radix_2/kernel_logN=12_reg16.cuh"
#include "./include/radix_2/kernel_logN=13.cuh"
#include "./include/test/kernel_forwardFFT_logN=3_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=4_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=5_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=6_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=7_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=8_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=9_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=10_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=11_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=12_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=13_axisID=0_axisUploadID=1.cuh"
#include "./include/radix_2/kernel_logN=14_upload=1.cuh"
#include "./include/radix_2/kernel_logN=14_upload=2.cuh"
#include "./include/radix_2/kernel_logN=15_upload=1.cuh"
#include "./include/radix_2/kernel_logN=15_upload=2.cuh"
#include "./include/radix_2/kernel_logN=16_upload=1.cuh"
#include "./include/radix_2/kernel_logN=16_upload=2.cuh"
#include "./include/radix_2/kernel_logN=17_upload=1.cuh"
#include "./include/radix_2/kernel_logN=17_upload=2.cuh"
#include "./include/radix_2/kernel_logN=18_upload=1.cuh"
#include "./include/radix_2/kernel_logN=18_upload=2.cuh"
#include "./include/radix_2/kernel_logN=19_upload=1.cuh"
#include "./include/radix_2/kernel_logN=19_upload=2.cuh"
#include "./include/test/kernel_forwardFFT_logN=14_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=14_axisID=0_axisUploadID=2.cuh"
#include "./include/test/kernel_forwardFFT_logN=15_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=15_axisID=0_axisUploadID=2.cuh"
#include "./include/test/kernel_forwardFFT_logN=16_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=16_axisID=0_axisUploadID=2.cuh"
#include "./include/test/kernel_forwardFFT_logN=17_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=17_axisID=0_axisUploadID=2.cuh"
#include "./include/test/kernel_forwardFFT_logN=18_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=18_axisID=0_axisUploadID=2.cuh"
#include "./include/test/kernel_forwardFFT_logN=19_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=19_axisID=0_axisUploadID=2.cuh"
#elif K_FFT == 2
#include "./include/fft.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN3_reg8.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN4_reg4.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN5_reg8.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN6_reg8.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN7_reg8.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN8_reg8.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN9_reg8.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN10_reg8.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN11_reg8.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN12_reg8.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN11_reg16.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN12_reg16.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN13_reg8.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN13_reg8.cuh"
#include "./include/test/kernel_forwardFFT_logN=3_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=4_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=5_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=6_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=7_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=8_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=9_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=10_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=11_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=12_axisID=0_axisUploadID=1.cuh"
#include "./include/test/kernel_forwardFFT_logN=13_axisID=0_axisUploadID=1.cuh"
// #include "./include/radix_2/kernel_logN=14_upload=1.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN14_reg8_upload=1.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN14_reg8_upload=2.cuh"
// #include "./include/radix_2/kernel_logN=14_upload=2.cuh"
// #include "./include/radix_2/kernel_logN=15_upload=1.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN15_reg8_upload=1.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN15_reg8_upload=2.cuh"
// #include "./include/radix_2/kernel_logN=15_upload=2.cuh"
// #include "./include/radix_2/kernel_logN=16_upload=1.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN16_reg8_upload=1.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN16_reg8_upload=2.cuh"
// #include "./include/radix_2/kernel_logN=16_upload=2.cuh"
// #include "./include/radix_2/kernel_logN=17_upload=1.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN17_reg16_upload=1.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN17_reg8_upload=2.cuh"
// #include "./include/radix_2/kernel_logN=17_upload=2.cuh"
// #include "./include/radix_2/kernel_logN=18_upload=1.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN18_reg8_upload=1.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN18_reg8_upload=2.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN18_reg8_upload=1.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN18_reg8_upload=2.cuh"
// #include "./include/radix_2/kernel_logN=18_upload=2.cuh"
// #include "./include/radix_2/kernel_logN=19_upload=1.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN19_reg8_upload=1.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN19_reg8_upload=1.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN19_reg32_upload=2.cuh"
// #include "./include/radix_2/kernel_logN=19_upload=2.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN20_reg32_upload=1.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN20_reg32_upload=2.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN21_reg32_upload=1.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN21_reg16_upload=2.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN22_reg16_upload=1.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN22_reg16_upload=2.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN23_reg16_upload=1.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN23_reg8_upload=2.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN23_reg16_upload=3.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN24_reg16_upload=1.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN24_reg16_upload=2.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN24_reg16_upload=3.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN25_reg16_upload=1.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN25_reg16_upload=2.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN25_reg8_upload=3.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN26_reg8_upload=1.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN26_reg16_upload=2.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN26_reg8_upload=3.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN27_reg8_upload=1.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN27_reg8_upload=2.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN27_reg8_upload=3.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN28_reg8_upload=1.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN28_reg8_upload=2.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN28_reg32_upload=3.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN29_reg32_upload=1.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN29_reg8_upload=2.cuh"
// #include "./include/radix_2_codegen/ft_fft_radix2_logN29_reg32_upload=3.cuh"

#include "./include/radix_2_codegen/ft_fft_radix2_logN23_upload=1.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN23_upload=2.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN23_upload=3.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN24_upload=1.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN24_upload=2.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN24_upload=3.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN25_upload=1.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN25_upload=2.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN25_upload=3.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN26_upload=1.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN26_upload=2.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN26_upload=3.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN27_upload=1.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN27_upload=2.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN27_upload=3.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN28_upload=1.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN28_upload=2.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN28_upload=3.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN29_upload=1.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN29_upload=2.cuh"
#include "./include/radix_2_codegen/ft_fft_radix2_logN29_upload=3.cuh"



// #include "./include/test/kernel_forwardFFT_logN=14_axisID=0_axisUploadID=1.cuh"
// #include "./include/test/kernel_forwardFFT_logN=14_axisID=0_axisUploadID=2.cuh"
// #include "./include/test/kernel_forwardFFT_logN=15_axisID=0_axisUploadID=1.cuh"
// #include "./include/test/kernel_forwardFFT_logN=15_axisID=0_axisUploadID=2.cuh"
// #include "./include/test/kernel_forwardFFT_logN=16_axisID=0_axisUploadID=1.cuh"
// #include "./include/test/kernel_forwardFFT_logN=16_axisID=0_axisUploadID=2.cuh"
// #include "./include/test/kernel_forwardFFT_logN=17_axisID=0_axisUploadID=1.cuh"
// #include "./include/test/kernel_forwardFFT_logN=17_axisID=0_axisUploadID=2.cuh"
// #include "./include/test/kernel_forwardFFT_logN=18_axisID=0_axisUploadID=1.cuh"
// #include "./include/test/kernel_forwardFFT_logN=18_axisID=0_axisUploadID=2.cuh"
// #include "./include/test/kernel_forwardFFT_logN=19_axisID=0_axisUploadID=1.cuh"
// #include "./include/test/kernel_forwardFFT_logN=19_axisID=0_axisUploadID=2.cuh"
// #include "./include/test/kernel_forwardFFT_logN=20_axisID=0_axisUploadID=1.cuh"
// #include "./include/test/kernel_forwardFFT_logN=20_axisID=0_axisUploadID=2.cuh"
// #include "./include/test/kernel_forwardFFT_logN=21_axisID=0_axisUploadID=1.cuh"
// #include "./include/test/kernel_forwardFFT_logN=21_axisID=0_axisUploadID=2.cuh"
// #include "./include/test/kernel_forwardFFT_logN=22_axisID=0_axisUploadID=1.cuh"
// #include "./include/test/kernel_forwardFFT_logN=22_axisID=0_axisUploadID=2.cuh"
// #include "./include/test/kernel_forwardFFT_logN=23_axisID=0_axisUploadID=1.cuh"
// #include "./include/test/kernel_forwardFFT_logN=23_axisID=0_axisUploadID=2.cuh"
// #include "./include/test/kernel_forwardFFT_logN=23_axisID=0_axisUploadID=3.cuh"
// #include "./include/test/kernel_forwardFFT_logN=24_axisID=0_axisUploadID=1.cuh"
// #include "./include/test/kernel_forwardFFT_logN=24_axisID=0_axisUploadID=2.cuh"
// #include "./include/test/kernel_forwardFFT_logN=24_axisID=0_axisUploadID=3.cuh"
// #include "./include/test/kernel_forwardFFT_logN=25_axisID=0_axisUploadID=1.cuh"
// #include "./include/test/kernel_forwardFFT_logN=25_axisID=0_axisUploadID=2.cuh"
// #include "./include/test/kernel_forwardFFT_logN=25_axisID=0_axisUploadID=3.cuh"
// #include "./include/test/kernel_forwardFFT_logN=26_axisID=0_axisUploadID=1.cuh"
// #include "./include/test/kernel_forwardFFT_logN=26_axisID=0_axisUploadID=2.cuh"
// #include "./include/test/kernel_forwardFFT_logN=26_axisID=0_axisUploadID=3.cuh"
// #include "./include/test/kernel_forwardFFT_logN=27_axisID=0_axisUploadID=1.cuh"
// #include "./include/test/kernel_forwardFFT_logN=27_axisID=0_axisUploadID=2.cuh"
// #include "./include/test/kernel_forwardFFT_logN=27_axisID=0_axisUploadID=3.cuh"
// #include "./include/test/kernel_forwardFFT_logN=28_axisID=0_axisUploadID=1.cuh"
// #include "./include/test/kernel_forwardFFT_logN=28_axisID=0_axisUploadID=2.cuh"
// #include "./include/test/kernel_forwardFFT_logN=28_axisID=0_axisUploadID=3.cuh"
// #include "./include/test/kernel_forwardFFT_logN=29_axisID=0_axisUploadID=1.cuh"
// #include "./include/test/kernel_forwardFFT_logN=29_axisID=0_axisUploadID=2.cuh"
// #include "./include/test/kernel_forwardFFT_logN=29_axisID=0_axisUploadID=3.cuh"
#endif