#include "./include/baseline_ft_sgemm.cuh"

#include "./include/sgemm_small.cuh"
#include "./include/sgemm_medium.cuh"
#include "./include/sgemm_large.cuh"
#include "./include/sgemm_tall.cuh"
#include "./include/sgemm_wide.cuh"
#include "./include/sgemm_huge.cuh"

#include "./include/ft_sgemm_small.cuh"
#include "./include/ft_sgemm_medium.cuh"
#include "./include/ft_sgemm_large.cuh"
#include "./include/ft_sgemm_tall.cuh"
#include "./include/ft_sgemm_wide.cuh"
#include "./include/ft_sgemm_huge.cuh"